### ISSUE TITLE
Not Compatible with Latest FAPI

### ISSUE THREAD

**Issue by ghost** [Minenash/Better-Mod-Button#5]
Better Mod Button is not compatible with the latest version of FAPI.  Please resolve this issue as it is affecting my other mods as I can't play them on the latest version.

**Comment by Minenash** [comment]
Modmenu 1.15 and above (which require the latest fapi) has made the mod obsolete. To get the same functionality, go to modmenu's new config screen and change the mod button type to adjacent

**Comment by Mhowser** [comment]
are you going to archive this repository?

**Comment by Minenash** [comment]
Yeah, I hadn't changed anything with it in months, so even though there's probably people who can't update to the newest version of modmenu, it's not like I'm going to change anything
